export enum SubscriptionPlan {
  ASPIRANTE = 'ASPIRANTE',
  PROFISSIONAL = 'PROFISSIONAL',
  BESTSELLER = 'BESTSELLER',
}

export enum SubscriptionStatus {
  ACTIVE = 'ACTIVE',
  PAST_DUE = 'PAST_DUE',
  CANCELLED = 'CANCELLED',
  PAUSED = 'PAUSED',
  TRIALING = 'TRIALING',
  UNPAID = 'UNPAID',
}

export enum BillingInterval {
  MONTHLY = 'MONTHLY',
  ANNUAL = 'ANNUAL',
}

export enum SubscriptionSource {
  STRIPE = 'STRIPE',
  ADMIN = 'ADMIN',
}

export enum CreditType {
  SUBSCRIPTION = 'SUBSCRIPTION',
  PURCHASE = 'PURCHASE',
  BONUS = 'BONUS',
  REFUND = 'REFUND',
}

export enum UserRole {
  USER = 'USER',
  ADMIN = 'ADMIN',
  EDITOR = 'EDITOR',
}

export enum BookStatus {
  DRAFT = 'DRAFT',
  PREVIEW_GENERATING = 'PREVIEW_GENERATING',
  PREVIEW = 'PREVIEW',
  PREVIEW_COMPLETING = 'PREVIEW_COMPLETING',
  PREVIEW_COMPLETED = 'PREVIEW_COMPLETED',
  PREVIEW_APPROVED = 'PREVIEW_APPROVED',
  QUEUED = 'QUEUED',
  GENERATING = 'GENERATING',
  GENERATED = 'GENERATED',
  ERROR = 'ERROR',
  CANCELLED = 'CANCELLED',
}

export enum BookCreationMode {
  SIMPLE = 'SIMPLE',
  GUIDED = 'GUIDED',
  ADVANCED = 'ADVANCED',
}

export enum ChapterStatus {
  PENDING = 'PENDING',
  GENERATING = 'GENERATING',
  GENERATED = 'GENERATED',
  ERROR = 'ERROR',
}

export enum ProductKind {
  CREDIT_PACK = 'CREDIT_PACK',
  BOOK_GENERATION = 'BOOK_GENERATION',
  ADDON_COVER = 'ADDON_COVER',
  ADDON_TRANSLATION = 'ADDON_TRANSLATION',
  ADDON_COVER_TRANSLATION = 'ADDON_COVER_TRANSLATION',
  ADDON_AMAZON_STANDARD = 'ADDON_AMAZON_STANDARD',
  ADDON_AMAZON_PREMIUM = 'ADDON_AMAZON_PREMIUM',
  ADDON_IMAGES = 'ADDON_IMAGES',
  ADDON_AUDIOBOOK = 'ADDON_AUDIOBOOK',
  ONE_TIME_BOOK = 'ONE_TIME_BOOK',
  SUBSCRIPTION_PLAN = 'SUBSCRIPTION_PLAN',
}

export enum PurchaseStatus {
  PENDING = 'PENDING',
  PAID = 'PAID',
  REFUNDED = 'REFUNDED',
  CHARGEBACK = 'CHARGEBACK',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}

export enum AddonStatus {
  PENDING = 'PENDING',
  QUEUED = 'QUEUED',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  ERROR = 'ERROR',
  CANCELLED = 'CANCELLED',
}

export enum WalletTransactionType {
  CREDIT_PURCHASE = 'CREDIT_PURCHASE',
  BOOK_GENERATION = 'BOOK_GENERATION',
  ADDON_PURCHASE = 'ADDON_PURCHASE',
  REFUND = 'REFUND',
  BONUS = 'BONUS',
  ADJUSTMENT = 'ADJUSTMENT',
  SUBSCRIPTION_CREDIT = 'SUBSCRIPTION_CREDIT',
}

export enum TranslationStatus {
  PENDING = 'PENDING',
  QUEUED = 'QUEUED',
  TRANSLATING = 'TRANSLATING',
  TRANSLATED = 'TRANSLATED',
  ERROR = 'ERROR',
  CANCELLED = 'CANCELLED',
}

export enum PublishingStatus {
  PREPARING = 'PREPARING',
  REVIEW = 'REVIEW',
  READY = 'READY',
  SUBMITTED = 'SUBMITTED',
  PUBLISHED = 'PUBLISHED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum FileType {
  PREVIEW_PDF = 'PREVIEW_PDF',
  FULL_PDF = 'FULL_PDF',
  EPUB = 'EPUB',
  DOCX = 'DOCX',
  COVER_IMAGE = 'COVER_IMAGE',
  COVER_TRANSLATED = 'COVER_TRANSLATED',
  AMAZON_PACKAGE = 'AMAZON_PACKAGE',
  AUDIOBOOK = 'AUDIOBOOK',
}

export enum NotificationType {
  BOOK_PREVIEW_READY = 'BOOK_PREVIEW_READY',
  BOOK_GENERATED = 'BOOK_GENERATED',
  BOOK_GENERATION_ERROR = 'BOOK_GENERATION_ERROR',
  ADDON_COMPLETED = 'ADDON_COMPLETED',
  ADDON_ERROR = 'ADDON_ERROR',
  TRANSLATION_COMPLETED = 'TRANSLATION_COMPLETED',
  PUBLISHING_UPDATE = 'PUBLISHING_UPDATE',
  CREDITS_ADDED = 'CREDITS_ADDED',
  CREDITS_LOW = 'CREDITS_LOW',
  CREDITS_EXPIRING = 'CREDITS_EXPIRING',
  SUBSCRIPTION_RENEWED = 'SUBSCRIPTION_RENEWED',
  SUBSCRIPTION_CANCELLED = 'SUBSCRIPTION_CANCELLED',
  SYSTEM = 'SYSTEM',
}
